GET http://localhost:5000/api/mazes
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhOdUNIYWlYdVN0MTF3dnB5RWFQdCJ9.eyJpc3MiOiJodHRwczovL2Rldi1uMHVqNXg0ay51cy5hdXRoMC5jb20vIiwic3ViIjoibzhoNVQ3aTNHbXBuT1JBNUlxTjhsS3hqN3ZBS0R0c0NAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZ3JpZHMvIiwiaWF0IjoxNjMyOTg1OTg0LCJleHAiOjE2MzMwNzIzODQsImF6cCI6Im84aDVUN2kzR21wbk9SQTVJcU44bEt4ajd2QUtEdHNDIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.NjBNUjHcrZ3I3HXPNptxS9eXC00qrOldS28pYfSYEMwcYMkgVplUhF6difoUD-KW-m2AcfeaAvIX-bdiLedslWg3F0VgsP6n-mU8UtomGeyTU41wWQxnsosnXPihNtlc1AOZrn7gD00AsEvgpNrCDsNUR9nJVbVloMBBWEdCuHhDgTWuZybReO2wwNu4Y3njLaF5PNitPYKcCSRhJfUv6-7DZq3sm55-CqfAUcTyXu9CX7tg_adK1PYHNtl2zzDPrdDyA7Cc4fA3yY030avDz993c7_bOu5a73ar1H22nKFkWblRCEfu0woCnOIsc79SiozfdjlH73fVVr8ZxMKWww

###
POST http://localhost:5000/api/mazes/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkxPS2Z5d3BUUXVjcFNQSFhfUWNzayJ9.eyJpc3MiOiJodHRwczovL2Rldi1lMW5vZm9teS51cy5hdXRoMC5jb20vIiwic3ViIjoieEZ2Sm8wRGxSanhIdEVhekZseE5EOTBKV3JPWG1aQUtAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZXhwcmVzcy5zYW1wbGUiLCJpYXQiOjE2MzYwMjEyNTksImV4cCI6MTYzNjEwNzY1OSwiYXpwIjoieEZ2Sm8wRGxSanhIdEVhekZseE5EOTBKV3JPWG1aQUsiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.rjLH89RtzFnMvxXZPYsLvW3A8pKY8A5ztAr_2f9-70kEXyWLuH9lHoIVmULplcUykN5XeBg4vvucNYKYbT-v6eO8wiMQTDoOdstZsxkaah28YS8tqZYEHXGwWqRi_IUxzlgTU333-RWAZb_ZAuKt4HlHJo3P5sIjgbE2C7Xm-Q8zzR4Cr6P_f2fAokh1Wrar5TfnR394qBzdoubxMWqLQf-4_EPK7Zam3F9Debi0QOIOzlRPjOGQv0ptCp85GyhOIL2lUULcBEXwhlB0ywPB9axSKCdsghntt2daWvANHgRlfl2O004UkRXSCaQxKBdw3zZ36P3rYkZmxau80xx42g
content-type: application/json

{   
    "usernameId": "Hitesh",
    "mazeBoard": [
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 555]
    ]
}

###
GET http://localhost:5000/api/mazes/google-oauth2|108518100713577969123
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhOdUNIYWlYdVN0MTF3dnB5RWFQdCJ9.eyJpc3MiOiJodHRwczovL2Rldi1uMHVqNXg0ay51cy5hdXRoMC5jb20vIiwic3ViIjoibzhoNVQ3aTNHbXBuT1JBNUlxTjhsS3hqN3ZBS0R0c0NAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZ3JpZHMvIiwiaWF0IjoxNjMyOTg1OTg0LCJleHAiOjE2MzMwNzIzODQsImF6cCI6Im84aDVUN2kzR21wbk9SQTVJcU44bEt4ajd2QUtEdHNDIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.NjBNUjHcrZ3I3HXPNptxS9eXC00qrOldS28pYfSYEMwcYMkgVplUhF6difoUD-KW-m2AcfeaAvIX-bdiLedslWg3F0VgsP6n-mU8UtomGeyTU41wWQxnsosnXPihNtlc1AOZrn7gD00AsEvgpNrCDsNUR9nJVbVloMBBWEdCuHhDgTWuZybReO2wwNu4Y3njLaF5PNitPYKcCSRhJfUv6-7DZq3sm55-CqfAUcTyXu9CX7tg_adK1PYHNtl2zzDPrdDyA7Cc4fA3yY030avDz993c7_bOu5a73ar1H22nKFkWblRCEfu0woCnOIsc79SiozfdjlH73fVVr8ZxMKWww